### PR TITLE
ci: e2e changes

### PR DESCRIPTION
**Pull request by lmouhib**
**Issue #, if available:**

## Description of changes:

This PR propose a way to parallelize some e2e tests to reduce the execution time of e2e.

**Checklist**

 

* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jeromevdl — APPROVED** [review]
Looks good to me

**Review by balabad — DISMISSED** [review]
The e2e test are failing with the following messages:
- Unable to retrieve Arn attribute for AWS::S3::Bucket, with error message Bucket not found
- Cluster already exists with name: data-platform

See [the logs](https://github.com/awslabs/data-solutions-framework-on-aws/actions/runs/7275325510) for details.
Probably, some tests do not support parallel execution as of now, so they need to be updated.

**Comment by lmouhib** [comment]
> The e2e test are failing with the following messages:
> 
>     * Unable to retrieve Arn attribute for AWS::S3::Bucket, with error message Bucket not found
> 
>     * Cluster already exists with name: data-platform
> 
> 
> See [the logs](https://github.com/awslabs/data-solutions-framework-on-aws/actions/runs/7275325510) for details. Probably, some tests do not support parallel execution as of now, so they need to be updated.

From the logs I can see the tests were executed with the old structure `npm run test:e2e`. The errors you point where from previous e2e runs.

**Comment by vgkowski** [comment]
dismissing @balabad review because I solved the error. It was coming from an EMR virtual cluster that failed to delete and then blocked all further e2e tests from succeeding.

**Review by vgkowski — APPROVED** [review]

**Pull request merged**
